# Generated by Django 5.0.6 on 2024-05-10 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EventModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Title')),
                ('article', models.TextField(verbose_name='Article')),
                ('date', models.DateTimeField(auto_now=True, verbose_name='Date')),
            ],
            options={
                'verbose_name_plural': 'Events',
            },
        ),
    ]
