# Generated by Django 5.0.6 on 2024-05-10 18:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='membermodel',
            name='sex',
            field=models.CharField(choices=[('Kişi', 'Kişi'), ('Qadın', 'Qadın')], default=1, max_length=10, verbose_name='Sex'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='membermodel',
            name='speciality',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='members.specialitymodel'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='membermodel',
            name='university',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='members.unievrsitymodel'),
            preserve_default=False,
        ),
    ]
