# Generated by Django 5.0.6 on 2024-05-10 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0002_membermodel_sex_membermodel_speciality_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='membermodel',
            name='speciality',
            field=models.CharField(max_length=200, verbose_name='Speciality'),
        ),
        migrations.AlterField(
            model_name='membermodel',
            name='university',
            field=models.CharField(max_length=200, verbose_name='University'),
        ),
        migrations.DeleteModel(
            name='SpecialityModel',
        ),
        migrations.DeleteModel(
            name='UnievrsityModel',
        ),
    ]
