# Generated by Django 5.0.6 on 2024-05-10 18:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0003_alter_membermodel_speciality_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SpecialityModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('speciality', models.CharField(max_length=200, verbose_name='Speciality')),
            ],
            options={
                'verbose_name_plural': 'Specialities',
            },
        ),
        migrations.CreateModel(
            name='UnievrsityModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('university', models.CharField(max_length=200, verbose_name='University')),
            ],
            options={
                'verbose_name_plural': 'Universities',
            },
        ),
        migrations.AlterField(
            model_name='membermodel',
            name='speciality',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='members.specialitymodel'),
        ),
        migrations.AlterField(
            model_name='membermodel',
            name='university',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='members.unievrsitymodel'),
        ),
    ]
